### ISSUE TITLE
大佬 工具有amd版本的吗

### ISSUE THREAD

**Issue by xiamo008** [xiaoxuan6/tools#1]
大佬你好，我想请教下工具有没有amd版本吗？我想放在服务器上，对接微信。然后识别特定群的二维码，解析成链接，方便后续使用

**Comment by xiaoxuan6** [comment]
> 大佬你好，我想请教下工具有没有amd版本吗？我想放在服务器上，对接微信。然后识别特定群的二维码，解析成链接，方便后续使用

`x86_64` 就是amd版本，但是你的需求使用这个不是好方法，你可以直接调用接口上传二维码图片识别更好

**Comment by xiamo008** [comment]
> > 大佬你好，我想请教下工具有没有amd版本吗？我想放在服务器上，对接微信。然后识别特定群的二维码，解析成链接，方便后续使用
> 
> `x86_64` 就是amd版本，但是你的需求使用这个不是好方法，你可以直接调用接口上传二维码图片识别更好

哦哦 好的，我刚接触这个 不太懂，求指导，这种接口，我该如何获取。https://github.com/mikoshu/gewechaty 我现在用的这个项目的ipad协议登录的微信

**Comment by xiaoxuan6** [comment]
> 哦 好的，我刚接触这个 不太懂，求指导，这种接口，我该如何获取。

https://www.toolnb.com/tools/qrcodeDecode.html

可以使用这个 `api` 接口, [api url](https://github.com/xiaoxuan6/tools/blob/main/ocr/ocr.go#L54)

**Comment by xiamo008** [comment]
> > 哦 好的，我刚接触这个 不太懂，求指导，这种接口，我该如何获取。
> 
> https://www.toolnb.com/tools/qrcodeDecode.html
> 
> 可以使用这个 `api` 接口, [api url](https://github.com/xiaoxuan6/tools/blob/main/ocr/ocr.go#L54)
好的，谢谢大佬，给个码，请大佬喝杯咖啡，耽误你时间了
